<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }
        .message { background: #e7f3ff; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .user-list { margin: 20px 0; }
        .user-item { background: #f8f9fa; padding: 10px; margin: 5px 0; border-radius: 4px; border-left: 4px solid #007bff; }
        .greeting { font-size: 1.2em; color: #28a745; }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ title }}</h1>
        
        {% if message %}
        <div class="message">
            <strong>Message:</strong> {{ message }}
        </div>
        {% endif %}
        
        {% if greeting %}
        <div class="greeting">
            {{ greeting }}
        </div>
        {% endif %}
        
        {% if name %}
        <p>Hello, <strong>{{ name }}</strong>! Welcome to our application.</p>
        {% endif %}
        
        {% if users %}
        <div class="user-list">
            <h3>User List:</h3>
            {% for user in users %}
            <div class="user-item">
                <strong>{{ user.name }}</strong> - {{ user.email }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        
        <hr>
        <p><small>Generated by TorrentPier Template Engine</small></p>
    </div>
</body>
</html>
